### ISSUE TITLE
HDPrivateKey derivation: version argument is not a buffer

### ISSUE THREAD

**Issue by Burtonium** [litecoin-project/litecore-lib#5]
The following code fails:

```
const HDPrivateKey = require('litecore-lib').HDPrivateKey;
const privKey = 'xprv...';

var parent = new HDPrivateKey(privKey);
var child_0_1_2h = parent.derive(0).derive(1).derive(2, true);
var copy_of_child_0_1_2h = parent.derive("m/0/1/2'");
assert(child_0_1_2h.xprivkey === copy_of_child_0_1_2h);

```

Giving me this error: 

`AssertionError: version argument is not a buffer
    at checkBuffer (/home/burton/depositor/node_modules/litecore-lib/lib/hdprivatekey.js:523:5)
    at Function.HDPrivateKey._validateBufferArguments (/home/burton/depositor/node_modules/litecore-lib/lib/hdprivatekey.js:529:3)
    at HDPrivateKey._buildFromBuffers (/home/burton/depositor/node_modules/litecore-lib/lib/hdprivatekey.js:461:16)
    at HDPrivateKey._buildFromObject (/home/burton/depositor/node_modules/litecore-lib/lib/hdprivatekey.js:376:15)
    at new HDPrivateKey (/home/burton/depositor/node_modules/litecore-lib/lib/hdprivatekey.js:61:10)
    at Object.<anonymous> (/home/burton/depositor/index.js:5:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)`

Any work arounds for this?

**Comment by Jacob-Nguyen** [comment]
Did you solve this issue?

**Comment by ultragtx** [comment]
The master and segwit branch are using old base58 prefixes, you can use branch v5.0 https://github.com/litecoin-project/litecore-lib/tree/v5.0 (not published to npm yet)

Or modify `xpubkey` `xprivkey` in `lib/networks.js` back to `0x0488b21e` and `0x0488ade4`.

**Comment by visionsofparadise** [comment]
i published the branch to npm as 'litecore-lib-v5' since this repo seems dead

**Comment by mastashake08** [comment]
> litecore-lib-v5

Yo you are a life save literally!

**Comment by red-name** [comment]
> litecore-lib-v5

You saved me! xpub and xprv works great!

**Comment by losh11** [comment]
Please do not use this in production. BitPay is soon releasing a
significantly updated version of this repo as part of the Bitcore stack
with LTC support. This repo will be archived very soon.
